    <link href="/assets/css/bootstrap.min.css" rel="Stylesheet" type="text/css" />
    <link href="/assets/font-awesome/4.5.0/css/font-awesome.min.css" rel="Stylesheet" type="text/css" />
    <link href="/assets/css/iconfont.css"  rel="stylesheet" />
    <link href="/assets/css/ace.min.css" rel="Stylesheet" type="text/css" />
    <link href="/assets/css/ace-skins.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="/assets/css/bootstrap-datepicker3.min.css" />

    <script src="/assets/js/jquery-2.1.4.min.js" type="text/javascript"></script>
    <script src="/assets/js/bootstrap.min.js" type="text/javascript" ></script>
    <script src="/assets/js/bootbox.js" type="text/javascript"></script>
    <script src="../../js/layer/layer.js" type="text/javascript"></script>
    <script src="../../js/layerCommon.js" type="text/javascript"></script>
    <script src="/assets/js/bootstrap-datepicker.min.js" type="text/javascript" ></script>
    <script src="/assets/js/ace-elements.min.js" type="text/javascript" ></script>
    <script src="/assets/js/ace.min.js" type="text/javascript" ></script>
    <!--[if lte IE 8]>
		<script src="/assets/js/html5shiv.min.js"></script>
		<script src="/assets/js/respond.min.js"></script>
	<![endif]-->